M48
; DRILL file {KiCad 7.0.6} date Thu Oct  5 23:13:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-05T23:13:57-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X5.0659Y-4.583
X5.1841Y-4.583
T2
X4.51Y-2.91
X4.51Y-4.55
X6.85Y-2.91
X6.85Y-4.55
T0
M30
